name: CI

on:
  pull_request:
    branches: [ master ]
    
jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Hello Demo
        run: echo Hello, world!
